// Configures the native Android & iOS projects generated by `flutter create`
// for Al-Huda: bundle identifiers, permissions, background audio, notification
// receivers, desugaring and the AudioServiceActivity.
//
// Run from the project root:  dart run tool/configure_platforms.dart
// The script is idempotent: running it twice produces the same result.

import 'dart:io';

const appId = 'com.alhuda.islamic.app';
const appLabel = 'الهدى';

void main() {
  final root = Directory.current;
  if (!File('${root.path}/pubspec.yaml').existsSync()) {
    stderr.writeln('Run this script from the project root (where pubspec.yaml is).');
    exit(1);
  }
  var ok = true;
  if (Directory('android').existsSync()) {
    ok &= _step('Android build.gradle', _configureGradle);
    ok &= _step('Android gradle.properties', _configureGradleProperties);
    ok &= _step('Android MainActivity', _configureMainActivity);
    ok &= _step('AndroidManifest.xml', _configureManifest);
    ok &= _step('Android resources (notification icon, launch theme)', _configureAndroidResources);
    ok &= _step('Android home-screen widgets', _configureWidgets);
  } else {
    stdout.writeln('! android/ not found – run `flutter create` first.');
  }
  if (Directory('ios').existsSync()) {
    ok &= _step('iOS Info.plist', _configureInfoPlist);
    ok &= _step('iOS bundle identifier', _configureIosBundleId);
  } else {
    stdout.writeln('! ios/ not found – skipped (fine on Windows/Linux).');
  }
  stdout.writeln(ok ? '\n✔ Platforms configured for $appId' : '\n✖ Some steps failed, see above.');
  if (!ok) exit(1);
}

bool _step(String name, void Function() action) {
  try {
    action();
    stdout.writeln('✔ $name');
    return true;
  } catch (e) {
    stdout.writeln('✖ $name: $e');
    return false;
  }
}

// ---------------------------------------------------------------- Android ---

void _configureGradle() {
  final kts = File('android/app/build.gradle.kts');
  final groovy = File('android/app/build.gradle');
  if (kts.existsSync()) {
    var s = kts.readAsStringSync();
    s = s.replaceAll(RegExp(r'namespace\s*=\s*"[^"]*"'), 'namespace = "$appId"');
    s = s.replaceAll(RegExp(r'applicationId\s*=\s*"[^"]*"'), 'applicationId = "$appId"');
    // flutter_local_notifications requires Android 7.0 (API 24)+.
    s = s.replaceAll('minSdk = flutter.minSdkVersion', 'minSdk = maxOf(24, flutter.minSdkVersion)');
    if (!s.contains('isCoreLibraryDesugaringEnabled')) {
      s = s.replaceFirstMapped(RegExp(r'compileOptions\s*\{'),
          (m) => '${m[0]}\n        isCoreLibraryDesugaringEnabled = true');
    }
    if (!s.contains('desugar_jdk_libs')) {
      s += '\ndependencies {\n    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.5")\n}\n';
    }
    // Release signing from android/key.properties (falls back to debug keys).
    if (!s.contains('keystoreProperties')) {
      s = 'import java.io.FileInputStream\nimport java.util.Properties\n\n$s';
      s = s.replaceFirst(
        RegExp(r'\nandroid\s*\{'),
        '''

val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    signingConfigs {
        create("release") {
            keyAlias = keystoreProperties["keyAlias"] as String?
            keyPassword = keystoreProperties["keyPassword"] as String?
            storeFile = (keystoreProperties["storeFile"] as String?)?.let { file(it) }
            storePassword = keystoreProperties["storePassword"] as String?
        }
    }
''',
      );
      s = s.replaceFirst(
        'signingConfig = signingConfigs.getByName("debug")',
        'signingConfig = if (keystorePropertiesFile.exists()) signingConfigs.getByName("release") else signingConfigs.getByName("debug")',
      );
    }
    kts.writeAsStringSync(s);
  } else if (groovy.existsSync()) {
    var s = groovy.readAsStringSync();
    s = s.replaceAll(RegExp(r'''namespace\s*=?\s*["'][^"']*["']'''), 'namespace = "$appId"');
    s = s.replaceAll(RegExp(r'''applicationId\s*=?\s*["'][^"']*["']'''), 'applicationId = "$appId"');
    s = s.replaceAll(RegExp(r'minSdk(Version)?\s*=?\s*flutter\.minSdkVersion'), 'minSdkVersion 24');
    if (!s.contains('coreLibraryDesugaringEnabled')) {
      s = s.replaceFirstMapped(RegExp(r'compileOptions\s*\{'),
          (m) => '${m[0]}\n        coreLibraryDesugaringEnabled true');
    }
    if (!s.contains('desugar_jdk_libs')) {
      s += "\ndependencies {\n    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'\n}\n";
    }
    groovy.writeAsStringSync(s);
  } else {
    throw 'android/app/build.gradle(.kts) not found';
  }
}

/// On Windows the pub cache (C:) and the project may live on different drives,
/// which breaks Kotlin incremental compilation ("different roots").
void _configureGradleProperties() {
  final file = File('android/gradle.properties');
  if (!file.existsSync()) throw 'android/gradle.properties not found';
  var s = file.readAsStringSync();
  if (!s.contains('kotlin.incremental')) {
    s = '${s.trimRight()}\n# Project and pub cache may be on different drives (Windows)\nkotlin.incremental=false\n';
    file.writeAsStringSync(s);
  }
}

const _splashColor = '#FF000000';

void _configureWidgets() {
  final src = Directory('tool/android_kotlin');
  final dest = Directory('android/app/src/main/kotlin/${appId.replaceAll('.', '/')}');
  dest.createSync(recursive: true);
  if (src.existsSync()) {
    for (final f in src.listSync().whereType<File>().where((f) => f.path.endsWith('.kt'))) {
      f.copySync('${dest.path}/${f.uri.pathSegments.last}');
    }
  }
  final preview = Directory('tool/android_kotlin_preview');
  if (Platform.environment['PREVIEW_WIDGETS'] == '1' && preview.existsSync()) {
    for (final f in preview.listSync().whereType<File>().where((f) => f.path.endsWith('.kt'))) {
      f.copySync('${dest.path}/${f.uri.pathSegments.last}');
    }
  }
  final manifest = File('android/app/src/main/AndroidManifest.xml');
  var s = manifest.readAsStringSync();
  if (!s.contains('PrayerWidgetProvider')) {
    const receivers = '''
        <!-- Home-screen widgets -->
        <receiver
            android:name=".PrayerWidgetProvider"
            android:exported="false"
            android:label="@string/widget_prayer_name">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE"/>
            </intent-filter>
            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@xml/widget_prayer_info"/>
        </receiver>
        <receiver
            android:name=".AyahWidgetProvider"
            android:exported="false"
            android:label="@string/widget_ayah_name">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE"/>
            </intent-filter>
            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@xml/widget_ayah_info"/>
        </receiver>
''';
    final idx = s.lastIndexOf('</application>');
    if (idx < 0) throw '</application> not found';
    s = s.replaceRange(idx, idx, '$receivers    ');
    manifest.writeAsStringSync(s);
  }
  if (!s.contains('AthkarWidgetProvider')) {
    const athkar = '''
        <receiver
            android:name=".AthkarWidgetProvider"
            android:exported="false"
            android:label="@string/widget_athkar_name">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE"/>
            </intent-filter>
            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@xml/widget_athkar_info"/>
        </receiver>
''';
    final idx = s.lastIndexOf('</application>');
    if (idx < 0) throw '</application> not found';
    s = s.replaceRange(idx, idx, '$athkar    ');
    manifest.writeAsStringSync(s);
  }
  // Widgets are laid out right-to-left (android:layoutDirection="rtl"),
  // which Android only honours when the app declares RTL support.
  if (!s.contains('supportsRtl')) {
    s = s.replaceFirst('<application', '<application\n        android:supportsRtl="true"');
  }
  // Prayer widget designs (same receiver shape, different layouts).
  const designs = {
    'PrayerNextWidgetProvider': 'widget_prayer_next',
    'PrayerMinimalWidgetProvider': 'widget_prayer_minimal',
    'PrayerListWidgetProvider': 'widget_prayer_list',
    'PrayerTileWidgetProvider': 'widget_prayer_tile',
  };
  designs.forEach((cls, res) {
    if (s.contains('.$cls"')) return;
    final receiver = '''
        <receiver
            android:name=".$cls"
            android:exported="false"
            android:label="@string/${res}_name">
            <intent-filter>
                <action android:name="android.appwidget.action.APPWIDGET_UPDATE"/>
            </intent-filter>
            <meta-data
                android:name="android.appwidget.provider"
                android:resource="@xml/${res}_info"/>
        </receiver>
''';
    final idx = s.lastIndexOf('</application>');
    if (idx < 0) throw '</application> not found';
    s = s.replaceRange(idx, idx, '$receiver    ');
  });
  // CI only: a screen that renders every widget, for screenshots.
  if (Platform.environment['PREVIEW_WIDGETS'] == '1' && !s.contains('WidgetPreviewActivity')) {
    const preview = '''
        <activity android:name=".WidgetPreviewActivity" android:exported="true"
            android:theme="@android:style/Theme.Material.NoActionBar"/>
        <activity android:name=".AutoProbeActivity" android:exported="true"
            android:theme="@android:style/Theme.Material.NoActionBar"/>
''';
    final idx = s.lastIndexOf('</application>');
    s = s.replaceRange(idx, idx, '$preview    ');
  }
  manifest.writeAsStringSync(s);
  if (!s.contains('AdhanService')) {
    const adhan = '''
        <!-- Adhan that plays even in silent/vibrate mode (alarm stream) -->
        <service
            android:name=".AdhanService"
            android:exported="false"
            android:foregroundServiceType="mediaPlayback"/>
        <receiver
            android:name=".AdhanReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
''';
    final idx = s.lastIndexOf('</application>');
    if (idx < 0) throw '</application> not found';
    s = s.replaceRange(idx, idx, '$adhan    ');
    manifest.writeAsStringSync(s);
  }
}

void _configureAndroidResources() {
  const res = 'android/app/src/main/res';
  // Monochrome status-bar icon used by prayer, Khatmah and audio notifications.
  final src = Directory('tool/android_res');
  if (src.existsSync()) {
    for (final f in src.listSync(recursive: true).whereType<File>()) {
      final rel = f.path.substring(src.path.length + 1).replaceAll('\\', '/');
      final dest = File('$res/$rel');
      dest.parent.createSync(recursive: true);
      f.copySync(dest.path);
    }
  }
  // Keep resources referenced only by name from Dart (resource shrinking).
  File('$res/raw/alhuda_keep.xml')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync('<?xml version="1.0" encoding="utf-8"?>\n'
        '<resources xmlns:tools="http://schemas.android.com/tools" '
        'tools:keep="@drawable/ic_stat_alhuda,@drawable/launch_background,@drawable/widget_*,@layout/widget_*,@xml/widget_*,@xml/automotive_app_desc,@drawable/car_*,@drawable/audio_service_*,@font/hafs,@raw/adhan_*,@raw/takbeer_*" />\n');
  File('$res/values/alhuda_colors.xml')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync('<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        '    <color name="alhuda_splash_bg">$_splashColor</color>\n</resources>\n');
  const launch = '<?xml version="1.0" encoding="utf-8"?>\n'
      '<layer-list xmlns:android="http://schemas.android.com/apk/res/android">\n'
      '    <item android:drawable="@color/alhuda_splash_bg" />\n'
      '</layer-list>\n';
  for (final d in ['drawable', 'drawable-v21']) {
    File('$res/$d/launch_background.xml')
      ..parent.createSync(recursive: true)
      ..writeAsStringSync(launch);
  }
  String styles({bool v31 = false}) => '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
      '    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">\n'
      '        <item name="android:windowBackground">@drawable/launch_background</item>\n'
      '${v31 ? '        <item name="android:windowSplashScreenBackground">@color/alhuda_splash_bg</item>\n' : ''}'
      '    </style>\n'
      '    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">\n'
      '        <item name="android:windowBackground">@color/alhuda_splash_bg</item>\n'
      '    </style>\n</resources>\n';
  for (final d in ['values', 'values-night']) {
    File('$res/$d/styles.xml')
      ..parent.createSync(recursive: true)
      ..writeAsStringSync(styles());
  }
  for (final d in ['values-v31', 'values-night-v31']) {
    File('$res/$d/styles.xml')
      ..parent.createSync(recursive: true)
      ..writeAsStringSync(styles(v31: true));
  }
}

void _configureMainActivity() {
  final srcRoots = [Directory('android/app/src/main/kotlin'), Directory('android/app/src/main/java')];
  final existing = <File>[];
  for (final dir in srcRoots.where((d) => d.existsSync())) {
    existing.addAll(dir
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('MainActivity.kt') || f.path.endsWith('MainActivity.java')));
  }
  final targetDir = Directory('android/app/src/main/kotlin/${appId.replaceAll('.', '/')}');
  targetDir.createSync(recursive: true);
  final target = File('${targetDir.path}/MainActivity.kt');
  for (final f in existing) {
    if (f.absolute.path != target.absolute.path) f.deleteSync();
  }
  target.writeAsStringSync('''package $appId

import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.view.Display
import com.ryanheise.audioservice.AudioServiceActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

// AudioServiceActivity keeps the Flutter engine alive for background playback
// and lock-screen media controls (required by audio_service).
class MainActivity : AudioServiceActivity() {
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        // Home-screen widgets: the app pushes prayer times and daily ayahs here.
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "alhuda/widgets").setMethodCallHandler { call, result ->
            when (call.method) {
                "update" -> {
                    WidgetStore.save(this, call.argument<String>("prayers"), call.argument<String>("ayahs"), call.argument<String>("style"))
                    WidgetStore.updateAll(this)
                    result.success(true)
                }
                else -> result.notImplemented()
            }
        }
        // Links from the owner's message (an update download, a page).
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "alhuda/app").setMethodCallHandler { call, result ->
            when (call.method) {
                "openUrl" -> {
                    try {
                        val intent = Intent(Intent.ACTION_VIEW, Uri.parse(call.argument<String>("url") ?: ""))
                        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                        startActivity(intent)
                        result.success(true)
                    } catch (e: Exception) {
                        result.success(false)
                    }
                }
                // Whether battery saving may hold the adhan back, and the maker
                // (each one hides the setting in a different place).
                "batteryStatus" -> {
                    val pm = getSystemService(android.content.Context.POWER_SERVICE) as android.os.PowerManager
                    val exempt = Build.VERSION.SDK_INT < Build.VERSION_CODES.M || pm.isIgnoringBatteryOptimizations(packageName)
                    result.success(mapOf("exempt" to exempt, "maker" to Build.MANUFACTURER.lowercase()))
                }
                "openAppSettings" -> {
                    try {
                        val intent = Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS, Uri.fromParts("package", packageName, null))
                        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                        startActivity(intent)
                        result.success(true)
                    } catch (e: Exception) {
                        result.success(false)
                    }
                }
                else -> result.notImplemented()
            }
        }
        // Adhan on the alarm stream (plays even when the phone is silent).
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "alhuda/adhan").setMethodCallHandler { call, result ->
            try {
                when (call.method) {
                    "schedule" -> {
                        AdhanAlarm.schedule(this, call.argument<List<Map<String, Any?>>>("items") ?: emptyList())
                        result.success(true)
                    }
                    "cancelAll" -> { AdhanAlarm.cancelAll(this); result.success(true) }
                    "playNow" -> {
                        AdhanAlarm.playNow(this, call.argument<String>("sound") ?: "",
                            call.argument<String>("title") ?: "", call.argument<String>("body") ?: "")
                        result.success(true)
                    }
                    "test" -> {
                        AdhanAlarm.scheduleTest(this, call.argument<Int>("seconds") ?: 10, call.argument<String>("sound") ?: "",
                            call.argument<String>("title") ?: "", call.argument<String>("body") ?: "")
                        result.success(true)
                    }
                    "stop" -> { AdhanAlarm.stop(this); result.success(true) }
                    else -> result.notImplemented()
                }
            } catch (e: Exception) {
                result.error("adhan", e.message, null)
            }
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        requestHighestRefreshRate()
    }

    override fun onResume() {
        super.onResume()
        requestHighestRefreshRate()
    }

    /// Many Android phones keep apps at 60 Hz unless they ask for more.
    /// Pick the fastest display mode (90/120/144/165 Hz) at the current resolution.
    private fun requestHighestRefreshRate() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) return
        @Suppress("DEPRECATION")
        val display: Display = (if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) this.display else windowManager.defaultDisplay)
            ?: return
        val current = display.mode
        val best = display.supportedModes
            .filter { it.physicalWidth == current.physicalWidth && it.physicalHeight == current.physicalHeight }
            .maxByOrNull { it.refreshRate } ?: return
        val params = window.attributes
        if (params.preferredDisplayModeId != best.modeId) {
            params.preferredDisplayModeId = best.modeId
            window.attributes = params
        }
    }
}
''');
}

void _configureManifest() {
  final file = File('android/app/src/main/AndroidManifest.xml');
  var s = file.readAsStringSync();

  const permissions = [
    'android.permission.INTERNET',
    'android.permission.ACCESS_NETWORK_STATE',
    'android.permission.ACCESS_FINE_LOCATION',
    'android.permission.ACCESS_COARSE_LOCATION',
    'android.permission.WAKE_LOCK',
    'android.permission.FOREGROUND_SERVICE',
    'android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK',
    'android.permission.POST_NOTIFICATIONS',
    'android.permission.RECEIVE_BOOT_COMPLETED',
    'android.permission.VIBRATE',
    'android.permission.SCHEDULE_EXACT_ALARM',
    'android.permission.RECORD_AUDIO',
  ];
  final missing = permissions.where((p) => !s.contains('"$p"')).map((p) => '    <uses-permission android:name="$p"/>').join('\n');
  if (missing.isNotEmpty) {
    s = s.replaceFirstMapped(RegExp(r'<manifest[^>]*>'), (m) => '${m[0]}\n$missing');
  }

  s = s.replaceFirst(RegExp(r'android:label="[^"]*"'), 'android:label="$appLabel"');
  // Text-to-speech (tafsir listening) must be visible on Android 11+.
  if (!s.contains('android.intent.action.TTS_SERVICE')) {
    const tts = '    <queries>\n        <intent>\n            <action android:name="android.intent.action.TTS_SERVICE"/>\n        </intent>\n        <intent>\n            <action android:name="android.speech.RecognitionService"/>\n        </intent>\n    </queries>\n';
    s = s.replaceFirst('<application', '$tts    <application');
  }
  // Some live Haram streams are plain http.
  if (!s.contains('usesCleartextTraffic')) {
    s = s.replaceFirst('<application', '<application\n        android:usesCleartextTraffic="true"');
  }

  // Android Auto: the app appears as a media source (Quran, reciters, radios).
  if (!s.contains('com.google.android.gms.car.application')) {
    final idx = s.lastIndexOf('</application>');
    s = s.replaceRange(idx, idx, '''        <meta-data
            android:name="com.google.android.gms.car.application"
            android:resource="@xml/automotive_app_desc"/>
    ''');
  }

  if (!s.contains('com.ryanheise.audioservice.AudioService')) {
    const services = '''
        <!-- Background audio (audio_service) -->
        <service
            android:name="com.ryanheise.audioservice.AudioService"
            android:foregroundServiceType="mediaPlayback"
            android:exported="true">
            <intent-filter>
                <action android:name="android.media.browse.MediaBrowserService"/>
            </intent-filter>
        </service>
        <receiver
            android:name="com.ryanheise.audioservice.MediaButtonReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON"/>
            </intent-filter>
        </receiver>
        <!-- Scheduled notifications (flutter_local_notifications) -->
        <receiver
            android:exported="false"
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver"/>
        <receiver
            android:exported="false"
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
''';
    final idx = s.lastIndexOf('</application>');
    if (idx < 0) throw '</application> not found';
    s = s.replaceRange(idx, idx, '$services    ');
  }
  file.writeAsStringSync(s);
}

// -------------------------------------------------------------------- iOS ---

void _configureInfoPlist() {
  final file = File('ios/Runner/Info.plist');
  var s = file.readAsStringSync();

  String setString(String src, String key, String value) {
    final re = RegExp('<key>$key</key>\\s*<string>[^<]*</string>');
    final entry = '<key>$key</key>\n\t<string>$value</string>';
    if (re.hasMatch(src)) return src.replaceFirst(re, entry);
    return _insertBeforeLastDict(src, '\t$entry\n');
  }

  s = setString(s, 'CFBundleDisplayName', appLabel);
  s = setString(s, 'NSLocationWhenInUseUsageDescription',
      'يحتاج تطبيق الهدى إلى موقعك لحساب مواقيت الصلاة بدقة وتحديد اتجاه القبلة.');
  s = setString(s, 'NSLocationAlwaysAndWhenInUseUsageDescription',
      'يستخدم تطبيق الهدى موقعك لحساب مواقيت الصلاة وتحديد اتجاه القبلة.');
  s = setString(s, 'NSMotionUsageDescription', 'يستخدم تطبيق الهدى مستشعرات الحركة لعرض بوصلة القبلة ثلاثية الأبعاد.');

  if (!s.contains('<key>UIBackgroundModes</key>')) {
    s = _insertBeforeLastDict(s, '\t<key>UIBackgroundModes</key>\n\t<array>\n\t\t<string>audio</string>\n\t\t<string>fetch</string>\n\t</array>\n');
  }
  if (!s.contains('<key>CFBundleLocalizations</key>')) {
    s = _insertBeforeLastDict(s, '\t<key>CFBundleLocalizations</key>\n\t<array>\n\t\t<string>ar</string>\n\t</array>\n');
  }
  file.writeAsStringSync(s);
}

String _insertBeforeLastDict(String src, String entry) {
  final idx = src.lastIndexOf('</dict>');
  if (idx < 0) throw 'Invalid plist';
  return src.replaceRange(idx, idx, entry);
}

void _configureIosBundleId() {
  final file = File('ios/Runner.xcodeproj/project.pbxproj');
  var s = file.readAsStringSync();
  s = s.replaceAllMapped(RegExp(r'PRODUCT_BUNDLE_IDENTIFIER = ([^;]+);'), (m) {
    final value = m[1]!;
    return value.endsWith('.RunnerTests')
        ? 'PRODUCT_BUNDLE_IDENTIFIER = $appId.RunnerTests;'
        : 'PRODUCT_BUNDLE_IDENTIFIER = $appId;';
  });
  file.writeAsStringSync(s);
}
